version: "3.3"

services:
  mysql:
    container_name: blog_mysql
    image: mysql:5.7
    networks:
      - blog
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:3306
    expose:
      - ${DB_PORT}
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
      ]
    restart: on-failure

networks:
  blog:
    driver: bridge

volumes:
  mysql:
