# Generated by Django 2.2.5 on 2019-09-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='age'),
        ),
    ]
