openapi: 3.0.0
info:
  version: "1.0.0"
  title: "API documentation\n You can also find admin panel at http://localhost:8000/admin"
tags:
  - name: "user"
    description: "Operations with user"
servers:
  - url: "http://localhost:8000"
paths:
  /api/v1/auth/user/:
    get:
      tags:
        - user
      $ref: ./accounts/paths.yaml#/getUser
      security:
        - Token: []
  /api/v1/auth/register/:
    post:
      tags:
        - user
      $ref: ./accounts/paths.yaml#/register
  /api/v1/auth/login/:
    post:
      tags:
        - user
      $ref: ./accounts/paths.yaml#/login
  /api/v1/auth/logout/:
    post:
      tags:
        - user
      $ref: ./accounts/paths.yaml#/logout
      security:
        - Token: []

components:
  securitySchemes:
    Token:
      description: "
      For accessing the API a valid token must be passed in all the queries in
      the 'Authorization' header.
      The following syntax must be used in the 'Authorization' header :
                      Value: apiKey"
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      $ref: './models.yaml#/User'